version: '3'

services:
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "root"
      
volumes:
  mongodata: 